############################################
#Server Port and Application Type #
############################################
server.port=9090
app.productName =REG_TECH
app.client=OLD
app.clientName=EQUITY
app.versionNo=V1.01
app.databaseType=${RG_DATA_BASE_TYPE}
server.error.include-message = always
 
############################################
#Vision Oracle Database Properties #
############################################
 
spring.datasource.url=${RG_VISION_DB_URL_STRING_N4}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${RG_VISION_DB_USER_NAME_N4}
spring.datasource.password=${RG_VISION_DB_PASSWORD_N4}
 
 
 
############################################
#Connection pooling properties(basic dbcp) #
############################################
 
spring.datasource.dbcp2.initial-size=10
spring.datasource.dbcp2.max-total=60
spring.datasource.dbcp2.min-idle=10
spring.datasource.dbcp2.max-idle=30
spring.datasource.dbcp2.test-on-borrow=true
spring.datasource.dbcp2.remove-abandoned-on-borrow=true
spring.datasource.dbcp2.min-evictable-idle-time-millis=300000
spring.datasource.dbcp2.cache-state=false
spring.datasource.dbcp2.time-between-eviction-runs-millis=100000
spring.datasource.dbcp2.log-abandoned=false
spring.datasource.dbcp2.log-expired-connections=false
 
############################################
#Security properties #
############################################
exclude.url=generateKeypair,forgotUsername,updateToken
 
provider.classname = jespa.ntlm.NtlmSecurityProvider
http.parameter.username.name = username
http.parameter.password.name = password
http.parameter.otpParameter.name = otpParameter 
http.parameter.logout.name = logout
http.parameter.anonymous.name = anon
fallback.location = UserLogin.jsp
excludes = *.gif, *.swf, error.jsp,UserLogin.jsp, *.png, *.JPG, *.ico, *.css, *.pdf,*.js, *.PNG, *.GIF
 
############################################
#JESPA Log Config    #
############################################
jespa.log.path = jespa.log
jespa.log.level = 1
jespa.account.canonicalForm = 3
# Replace the following with properties determined in Step 1 of Installation
# Generated by the Jespa Setup Wizard from IOPLEX Software on 6/10/2011
jespa.bindstr = SUNOIDA.com
jespa.dns.servers = 10.16.1.25
jespa.dns.site = Default-First-Site-Name
jespa.service.acctname = jespa1$@SUNOIDA.COM
jespa.service.password = Sunoida123
 
skipAuth=false
appName=/VisionBI
isNoLogin=false
ldapAuth = true
 
adServers=skip
 
 
twoFactorAuthFlag =${RG_TWO_FATCOR_AUTH_FLAG}
#false
#E,C,S
twoFactorAuthMethod=${RG_TWO_FATCOR_AUTH_METHOD}
 
 
############################################
#FTP/SFTP Configuration #
############################################
 
ftp.blockSize=4096
ftp.hostName=192.168.30.21
ftp.userName=vision
ftp.password=vision$12345
ftp.xlUploadhostName=10.16.1.101
ftp.xlUploaduserName=vision
ftp.xlUploadpassword=vision123
ftp.uploadDir=xlupload_data
ftp.downloadDir=xlupload_logs
#ftp.timezoneId=Africa/Nairobi
ftp.dateFormate=dd MMM yyyy
#WINDOWS, VMS, UNIX, MVS, OS/2, OS/400
ftp.serverType=WINDOWS
ftp.securedFtp=true
ftp.prompt=$
ftp.knownHostsFileName=c\:known_hosts
ftp.processDir=/home/vision/execs
ftp.scriptDir=/home/vision/scripts
#File TYPE ASCII(0) OR BINARY(2)
ftp.fileType=2
nonAdFtp.serverType=WINDOWS
############################################
#Mailing Property #
############################################
 
# Local #
#spring.mail.host=smtp.gmail.com
 
# Local # 
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=test
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
 
############################################
#Mail HTML Freemarker Templete #
############################################
 
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.freemarker.cache=false
spring.freemarker.check-template-location=true
spring.freemarker.content-type=text/html
spring.freemarker.charset=UTF-8
spring.mvc.dispatch-options-request=true
spring.servlet.multipart.max-file-size = 100MB
spring.servlet.multipart.max-request-size = 100MB
 
#############################################
#BUILD ENGINES SWITCHES#
#############################################
schedule.genBuild = ${RG_SCHEDULE_GEN_BULID}
schedule.adfBuild = ${SCHEDULE_ADF_BUILD}
schedule.rgBuild = ${SCHEDULE_RG_BUILD}
schedule.upload =${RG_UPLOAD_SCHEDULER}
app.cloud=N
app.decimal.precision=Y
email.alerts =${RG_EMAIL_ALERT}
adfEmail.alerts =${RG_ADF_EMAIL_ALERT}
esclation.alerts =${RG_ESCALATION_ALERT}
############################################# 
upload.scheduler=${SCHEDULE_UPLOAD}
upload.xluploadLogFilePath =${RG_XL_UPLOAD_FILE_LOGPATH}
upload.xluploadDataFilePath = ${RG_XL_UPLOAD_FILE_DATAPATH}
mail.scheduler=${RG_MAIL_SCHEDULER}
#############################################
 
app.client.id =${RG_CLIENT_ID}
app.alient.sceret=${RG_ALIENT_SCERET}
app.client.scope=${RG_CLIENT_SCOPE}
# RG FATCA JAR memory settings
crs.fatca.jar.memory.min=512m
crs.fatca.jar.memory.max=2048m
mdm.scheduler=${RG_MDM_SCHEDULER_FLAG}
 
 
app.cors.allowed-origins=*
 
 
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.max-age=3600
app.cors.allow-credentials=false
 
#########FATCA Encryption for Download ###########
fatca.encrypt.xml=${RG_FATCA_ENCRYPT_XML}